<script setup lang="ts">
import { reactive, watch } from 'vue'
import type { Brand, Category, ProductFilters } from '../../../shared/types/product'
interface FilterForm { brand:string; category:string; color:string; minPrice:string; maxPrice:string }
const props=defineProps<{filters:ProductFilters;brands:Brand[];categories:Category[];colors:string[]}>(); const emit=defineEmits<{apply:[filters:ProductFilters];reset:[]}>(); const form=reactive<FilterForm>({brand:'',category:'',color:'',minPrice:'',maxPrice:''})
const copy=(filters:ProductFilters):void=>{form.brand=filters.brand??'';form.category=filters.category??'';form.color=filters.color??'';form.minPrice=filters.minPrice===undefined?'':String(filters.minPrice);form.maxPrice=filters.maxPrice===undefined?'':String(filters.maxPrice)}
watch(()=>props.filters,copy,{deep:true,immediate:true}); const price=(value:string):number|undefined=>{const n=Number(value.trim());return value.trim()&&Number.isFinite(n)&&n>=0?n:undefined}; const apply=():void=>{const filters:ProductFilters={};const min=price(form.minPrice);const max=price(form.maxPrice);if(form.brand)filters.brand=form.brand;if(form.category)filters.category=form.category;if(form.color)filters.color=form.color;if(min!==undefined)filters.minPrice=min;if(max!==undefined)filters.maxPrice=max;emit('apply',filters)}; const reset=():void=>{copy({});emit('reset')}
</script>
<template><form class="ui-card grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-1" @submit.prevent="apply"><div><label class="mb-1 block text-sm font-semibold" for="brand">Thương hiệu</label><select id="brand" v-model="form.brand" class="w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-white px-3"><option value="">Tất cả thương hiệu</option><option v-for="brand in brands" :key="brand.value" :value="brand.value">{{ brand.label }}</option></select></div><div><label class="mb-1 block text-sm font-semibold" for="category">Loại sản phẩm</label><select id="category" v-model="form.category" class="w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-white px-3"><option value="">Tất cả loại sản phẩm</option><option v-for="category in categories" :key="category.value" :value="category.value">{{ category.label }}</option></select></div><div><label class="mb-1 block text-sm font-semibold" for="color">Màu sắc</label><select id="color" v-model="form.color" class="w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-white px-3"><option value="">Tất cả màu sắc</option><option v-for="color in colors" :key="color" :value="color">{{ color }}</option></select></div><div class="grid grid-cols-2 gap-3 sm:col-span-2 lg:col-span-1"><div><label class="mb-1 block text-sm font-semibold" for="minPrice">Giá tối thiểu</label><input id="minPrice" v-model="form.minPrice" class="w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] px-3" inputmode="numeric" min="0" type="number"></div><div><label class="mb-1 block text-sm font-semibold" for="maxPrice">Giá tối đa</label><input id="maxPrice" v-model="form.maxPrice" class="w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] px-3" inputmode="numeric" min="0" type="number"></div></div><div class="flex gap-2 sm:col-span-2 lg:col-span-1"><button class="rounded-[var(--radius-sm)] bg-[var(--color-primary)] px-4 py-2 text-sm font-semibold text-white hover:bg-[var(--color-primary-hover)]" type="submit">Áp dụng</button><button class="rounded-[var(--radius-sm)] border border-[var(--color-border)] px-4 py-2 text-sm font-semibold hover:bg-[var(--color-surface-muted)]" type="button" @click="reset">Đặt lại</button></div></form></template>
