import brandsData from '../data/brands.json'
import categoriesData from '../data/categories.json'
import productsData from '../data/products.json'
import type { Brand, Category, Product, ProductFilters } from '../types/product'
const products = productsData as Product[]
const brands: readonly Brand[] = brandsData
const categories: readonly Category[] = categoriesData
const normal = (value: string): string => value.trim().toLocaleLowerCase('vi-VN')
const unique = (values: readonly string[]): string[] => [...new Set(values)]
export class ProductFilterValidationError extends Error { constructor(message: string) { super(message); this.name = 'ProductFilterValidationError' } }
export const getAllProducts = (): Product[] => [...products]
export const getProductBySlug = (slug: string): Product | undefined => products.find((product) => product.slug === slug.trim())
export const filterProducts = (filters: ProductFilters = {}): Product[] => products.filter((product) => (!filters.brand || normal(product.brand) === normal(filters.brand)) && (!filters.category || normal(product.category) === normal(filters.category)) && (!filters.color || normal(product.color) === normal(filters.color)) && (filters.minPrice === undefined || product.price >= filters.minPrice) && (filters.maxPrice === undefined || product.price <= filters.maxPrice))
export const getRelatedProducts = (product: Product, limit = 4): Product[] => { const ids = unique([...products.filter((item) => item.id !== product.id && item.category === product.category), ...products.filter((item) => item.id !== product.id && item.brand === product.brand)].map((item) => item.id)); return ids.map((id) => products.find((item) => item.id === id)).filter((item): item is Product => item !== undefined).slice(0, Math.min(Math.max(limit, 0), 4)) }
export const getAvailableFilters = () => { const prices = products.map((product) => product.price); return { brands: brands.map((brand) => ({ ...brand })), categories: categories.map((category) => ({ ...category })), colors: unique(products.map((product) => product.color)), priceRange: { min: Math.min(...prices), max: Math.max(...prices) } } }
const value = (query: Record<string, unknown>, field: string): string | undefined => { const item = query[field]; if (item === undefined) return undefined; if (typeof item !== 'string') throw new ProductFilterValidationError(`Query parameter "${field}" must be a single value.`); const trimmed = item.trim(); if (!trimmed) throw new ProductFilterValidationError(`Query parameter "${field}" cannot be empty.`); return trimmed }
const allowed = (item: string, options: readonly string[], field: string): string => { const found = options.find((option) => normal(option) === normal(item)); if (!found) throw new ProductFilterValidationError(`Query parameter "${field}" is not allowed.`); return found }
const price = (item: string, field: string): number => { const parsed = Number(item); if (!Number.isFinite(parsed) || parsed < 0) throw new ProductFilterValidationError(`Query parameter "${field}" must be a non-negative number.`); return parsed }
export const parseProductFilters = (query: Record<string, unknown>): ProductFilters => { const available = getAvailableFilters(); const result: ProductFilters = {}; const brand = value(query, 'brand'); const category = value(query, 'category'); const color = value(query, 'color'); const minPrice = value(query, 'minPrice'); const maxPrice = value(query, 'maxPrice'); if (brand) result.brand = allowed(brand, available.brands.map((item) => item.value), 'brand'); if (category) result.category = allowed(category, available.categories.map((item) => item.value), 'category'); if (color) result.color = allowed(color, available.colors, 'color'); if (minPrice) result.minPrice = price(minPrice, 'minPrice'); if (maxPrice) result.maxPrice = price(maxPrice, 'maxPrice'); if (result.minPrice !== undefined && result.maxPrice !== undefined && result.minPrice > result.maxPrice) throw new ProductFilterValidationError('Query parameter "minPrice" cannot be greater than "maxPrice".'); return result }
