<script setup lang="ts">
import { computed, watch } from 'vue'
import type { ProductFilters, ProductListResponse } from '../../shared/types/product'
import { filtersToQuery, normalizeProductQuery } from '../utils/product-filters'
import { productsPageMetadata } from '../utils/product-metadata'
import { useProductStore } from '../stores/product'
useSeoMeta(productsPageMetadata)
const route = useRoute(); const router = useRouter(); const productStore = useProductStore(); const apiQuery = computed(() => normalizeProductQuery(route.query))
watch(() => route.query, (query) => productStore.restoreFiltersFromQuery(query), { immediate: true })
const { data, error, status, refresh } = await useAsyncData<ProductListResponse>('product-list', () => $fetch('/api/products', { query: apiQuery.value }), { watch: [apiQuery] })
watch(data, (list) => { if (list) productStore.setProductList(list) }, { immediate: true })
const applyFilters = async (filters: ProductFilters): Promise<void> => { productStore.setFilters(filters); await router.push({ query: filtersToQuery(filters) }) }
const resetFilters = async (): Promise<void> => { productStore.resetFilters(); await router.push({ query: {} }) }
const retry = (): void => { void refresh() }
</script>
<template><section class="site-container py-8 sm:py-10"><nav aria-label="Breadcrumb" class="text-sm text-[var(--color-text-muted)]"><NuxtLink class="hover:text-[var(--color-primary)]" to="/">Trang chủ</NuxtLink> <span aria-hidden="true">/</span> <span>Sản phẩm</span></nav><div class="mt-4"><p class="text-sm font-bold uppercase tracking-[.16em] text-[var(--color-primary)]">Danh mục</p><h1 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Tất cả sản phẩm</h1><p class="mt-3 text-[var(--color-text-muted)]">Lọc dữ liệu trực tiếp từ Nitro API mà không tải lại toàn bộ trang.</p></div><div class="mt-8 grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]"><aside class="lg:sticky lg:top-24 lg:self-start"><h2 class="mb-3 text-lg font-black">Bộ lọc</h2><ProductFilters :brands="data?.availableBrands ?? []" :categories="data?.availableCategories ?? []" :colors="data?.availableColors ?? []" :filters="productStore.filters" @apply="applyFilters" @reset="resetFilters" /></aside><div><div class="ui-card flex flex-wrap items-center justify-between gap-3 p-4"><p aria-live="polite" class="text-sm text-[var(--color-text-muted)]"><template v-if="data">Tìm thấy <strong class="text-[var(--color-text)]">{{ data.total }}</strong> sản phẩm</template><template v-else>Đang tải kết quả</template></p><button v-if="Object.keys(productStore.filters).length" class="text-sm font-semibold text-[var(--color-primary)] hover:underline" type="button" @click="resetFilters">Xóa toàn bộ filter</button></div><ProductGridSkeleton v-if="status === 'pending'" class="mt-5"/><section v-else-if="error" class="ui-card mt-5 p-6" aria-labelledby="products-error-title"><h2 id="products-error-title" class="font-semibold text-[var(--color-danger)]">Không thể tải danh sách sản phẩm</h2><p class="mt-2 text-sm text-[var(--color-text-muted)]">Vui lòng kiểm tra lại điều kiện lọc hoặc thử lại.</p><button class="mt-4 rounded-[var(--radius-sm)] bg-[var(--color-primary)] px-4 py-2 font-semibold text-white" type="button" @click="retry">Thử lại</button></section><ProductEmptyState v-else-if="data && data.total === 0" class="mt-5" @reset="resetFilters"/><ProductGrid v-else-if="data" :categories="data.availableCategories" :products="data.items" class="mt-5"/></div></div></section></template>
